//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitePanel.Portal.ProviderControls {
    
    public partial class ArgoMail_EditAccount {
        protected WebsitePanel.Portal.CollapsiblePanel secAutoresponder;
        protected System.Web.UI.WebControls.Panel AutoresponderPanel;
        protected System.Web.UI.WebControls.Label lblResponderEnabled;
        protected System.Web.UI.WebControls.CheckBox chkResponderEnabled;
        protected System.Web.UI.WebControls.Label lblSubject;
        protected System.Web.UI.WebControls.TextBox txtSubject;
        protected System.Web.UI.WebControls.Label lblMessage;
        protected System.Web.UI.WebControls.TextBox txtMessage;
        protected WebsitePanel.Portal.CollapsiblePanel secForwarding;
        protected System.Web.UI.WebControls.Panel ForwardingPanel;
        protected System.Web.UI.WebControls.Label lblForwardTo;
        protected System.Web.UI.WebControls.TextBox txtForward;
    }
}
