//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitePanel.Portal {
    
    public partial class SharePointUsersEditUser {
        protected System.Web.UI.WebControls.Label lblUserName;
        protected WebsitePanel.Portal.UsernameControl usernameControl;
        protected System.Web.UI.WebControls.Label lblUserPassword;
        protected WebsitePanel.Portal.PasswordControl passwordControl;
        protected WebsitePanel.Portal.CollapsiblePanel secGroups;
        protected System.Web.UI.WebControls.Panel GroupsPanel;
        protected System.Web.UI.HtmlControls.HtmlTable tblGroups;
        protected System.Web.UI.WebControls.CheckBoxList dlGroups;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.WebControls.Button btnCancel;
        protected System.Web.UI.WebControls.Button btnDelete;
    }
}
