//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitePanel.Portal {
    
    public partial class SpaceSettingsNameServers {
        protected WebsitePanel.Portal.CollapsiblePanel secNameServers;
        protected System.Web.UI.WebControls.Panel NameServersPanel;
        protected System.Web.UI.WebControls.Label lblNameServers;
        protected WebsitePanel.Portal.UserControls.EditDomainsList domainsList;
    }
}
