//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitePanel.Portal.ExchangeServer {
    
    public partial class ExchangePublicFolderGeneralSettings {
        protected WebsitePanel.Portal.EnableAsyncTasksSupport asyncTasks;
        protected WebsitePanel.Portal.ExchangeServer.UserControls.Breadcrumb breadcrumb;
        protected WebsitePanel.Portal.ExchangeServer.UserControls.Menu menu;
        protected System.Web.UI.WebControls.Image Image1;
        protected System.Web.UI.WebControls.Localize locTitle;
        protected System.Web.UI.WebControls.Literal litDisplayName;
        protected WebsitePanel.Portal.ExchangeServer.UserControls.PublicFolderTabs tabs;
        protected WebsitePanel.Portal.UserControls.SimpleMessageBox messageBox;
        protected System.Web.UI.WebControls.Localize locName;
        protected System.Web.UI.WebControls.TextBox txtName;
        protected System.Web.UI.WebControls.RequiredFieldValidator valDisplayName;
        protected System.Web.UI.WebControls.Button btnMailEnable;
        protected System.Web.UI.WebControls.Button btnMailDisable;
        protected System.Web.UI.WebControls.Localize locAuthors;
        protected WebsitePanel.Portal.ExchangeServer.UserControls.AccountsList authors;
        protected System.Web.UI.WebControls.CheckBox chkHideAddressBook;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.WebControls.ValidationSummary ValidationSummary1;
        protected System.Web.UI.WebControls.Localize FormComments;
    }
}
