//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitePanel.Portal {
    
    public partial class UsernamePolicyEditor {
        protected System.Web.UI.UpdatePanel UsernamePolicyPanel;
        protected System.Web.UI.WebControls.CheckBox chkEnabled;
        protected System.Web.UI.HtmlControls.HtmlTable PolicyTable;
        protected System.Web.UI.WebControls.Label lblAllowedSymbols;
        protected System.Web.UI.WebControls.TextBox txtAllowedSymbols;
        protected System.Web.UI.WebControls.Label lblDefaultAllowedSymbols;
        protected System.Web.UI.WebControls.Label lblMinimumLength;
        protected System.Web.UI.WebControls.TextBox txtMinimumLength;
        protected System.Web.UI.WebControls.RequiredFieldValidator valRequireMinLength;
        protected System.Web.UI.WebControls.RegularExpressionValidator valCorrectMinLength;
        protected System.Web.UI.WebControls.Label lblMaximumLength;
        protected System.Web.UI.WebControls.TextBox txtMaximumLength;
        protected System.Web.UI.WebControls.RequiredFieldValidator valRequireMaxLength;
        protected System.Web.UI.WebControls.RegularExpressionValidator valCorrectMaxLength;
        protected System.Web.UI.WebControls.Label lblPrefix;
        protected System.Web.UI.WebControls.TextBox txtPrefix;
        protected System.Web.UI.WebControls.Label lblSuffix;
        protected System.Web.UI.WebControls.TextBox txtSuffix;
        protected System.Web.UI.WebControls.Label lblSuffixVars;
    }
}
