//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitePanel.Portal.SkinControls {
    
    public partial class SignedInUser {
        protected System.Web.UI.WebControls.Panel AnonymousPanel;
        protected System.Web.UI.WebControls.HyperLink lnkSignIn;
        protected System.Web.UI.WebControls.Panel LoggedPanel;
        protected System.Web.UI.WebControls.Literal litUsername;
        protected System.Web.UI.WebControls.HyperLink lnkEditUserDetails;
        protected System.Web.UI.WebControls.LinkButton cmdSignOut;
    }
}
