//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitePanel.Portal.ProviderControls {
    
    public partial class Gene6FTP_Settings {
        protected System.Web.UI.WebControls.Label lblInstallFolder;
        protected System.Web.UI.WebControls.TextBox txtInstallFolder;
        protected System.Web.UI.WebControls.Label lblSite;
        protected System.Web.UI.WebControls.DropDownList ddlFtpSite;
        protected System.Web.UI.WebControls.Label lblBuildUncFilesPath;
        protected System.Web.UI.WebControls.CheckBox chkBuildUncFilesPath;
    }
}
