//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitePanel.Portal.ProviderControls {
    
    public partial class SmarterStats_EditSite {
        protected System.Web.UI.WebControls.Label lblSiteID;
        protected System.Web.UI.WebControls.TextBox txtSiteId;
        protected System.Web.UI.WebControls.Label lblSiteStatus;
        protected System.Web.UI.WebControls.Literal litSiteStatus;
        protected System.Web.UI.WebControls.Label lblSiteUsers;
        protected System.Web.UI.WebControls.Button btnAdd;
        protected System.Web.UI.WebControls.GridView gvUsers;
    }
}
