//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitePanel.Portal.ProviderControls {
    
    public partial class AWStats_Settings {
        protected System.Web.UI.WebControls.Label lblCgiBinFolder;
        protected System.Web.UI.WebControls.TextBox txtAwStatsFolder;
        protected System.Web.UI.WebControls.Label lblBatchFileName;
        protected System.Web.UI.WebControls.TextBox txtBatchFileName;
        protected System.Web.UI.WebControls.Label lblLineTemplate;
        protected System.Web.UI.WebControls.TextBox txtBatchLineTemplate;
        protected System.Web.UI.WebControls.Label lblConfigFileName;
        protected System.Web.UI.WebControls.TextBox txtConfigFileName;
        protected System.Web.UI.WebControls.Label lblFileTemplate;
        protected System.Web.UI.WebControls.TextBox txtConfigFileTemplate;
        protected System.Web.UI.WebControls.Label lblFileTemplatePath;
        protected System.Web.UI.WebControls.TextBox txtConfigFileTemplatePath;
        protected System.Web.UI.WebControls.Label lblBuildUncLogsPath;
        protected System.Web.UI.WebControls.CheckBox chkBuildUncLogsPath;
        protected System.Web.UI.WebControls.Label lblStatsUrl;
        protected System.Web.UI.WebControls.TextBox txtStatsUrl;
    }
}
