'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Reflection
Imports System.Runtime.CompilerServices
Imports System.Runtime.InteropServices
<Assembly: AssemblyCompany("SMB SAAS Systems Inc."),  _
 Assembly: AssemblyCopyright("Copyright © 2011 SMB SAAS Systems Inc."),  _
 Assembly: AssemblyVersion("1.2.0.0"),  _
 Assembly: AssemblyFileVersion("1.2.0.29"),  _
 Assembly: AssemblyInformationalVersion("1.2.0 Beta")> 

