//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitePanel.Portal {
    
    public partial class LoginForgotPassword {
        protected System.Web.UI.WebControls.Label lblUsername;
        protected System.Web.UI.WebControls.TextBox txtUsername;
        protected System.Web.UI.WebControls.RequiredFieldValidator usernameValidator;
        protected System.Web.UI.WebControls.Button btnSend;
        protected System.Web.UI.WebControls.LinkButton cmdBack;
    }
}
