//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitePanel.Portal {
    
    public partial class ServersEditEventViewer {
        protected WebsitePanel.Portal.ServerHeaderControl ServerHeaderControl1;
		protected System.Web.UI.UpdatePanel updatePanelUsers;
        protected System.Web.UI.WebControls.DropDownList ddlLogNames;
        protected System.Web.UI.WebControls.Button btnClearLog;
        protected System.Web.UI.WebControls.GridView gvEntries;
        protected System.Web.UI.WebControls.ObjectDataSource odsLogEntries;
        protected System.Web.UI.WebControls.Button btnCancel;
    }
}
