//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitePanel.Portal {
    
    public partial class SpaceEditAddon {
        protected System.Web.UI.WebControls.Label lblMessage;
        protected System.Web.UI.WebControls.Label lblAddon;
        protected System.Web.UI.WebControls.DropDownList ddlPlan;
        protected System.Web.UI.WebControls.RequiredFieldValidator planValidator;
        protected System.Web.UI.WebControls.Label lblQuantity;
        protected System.Web.UI.WebControls.TextBox txtQuantity;
        protected System.Web.UI.WebControls.RequiredFieldValidator valQuantity;
        protected System.Web.UI.WebControls.Label lblStatus;
        protected System.Web.UI.WebControls.DropDownList ddlStatus;
        protected System.Web.UI.WebControls.Label lblCreationDate;
        protected WebsitePanel.Portal.CalendarControl PurchaseDate;
        protected System.Web.UI.WebControls.Label lblComments;
        protected System.Web.UI.WebControls.TextBox txtComments;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.WebControls.Button btnCancel;
        protected System.Web.UI.WebControls.Button btnDelete;
    }
}
