//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitePanel.Portal {
    
    public partial class SqlBackupDatabase {
        protected System.Web.UI.WebControls.Literal litDatabaseName;
        protected System.Web.UI.WebControls.Label lblBackupFileName;
        protected System.Web.UI.WebControls.TextBox txtBackupName;
        protected System.Web.UI.WebControls.RequiredFieldValidator validatorUserName;
        protected System.Web.UI.WebControls.Label lblBackupOptions;
        protected System.Web.UI.WebControls.CheckBox chkZipBackup;
        protected System.Web.UI.WebControls.Label lblBackupDestination;
        protected System.Web.UI.WebControls.RadioButton rbDownload;
        protected System.Web.UI.WebControls.RadioButton rbCopy;
        protected WebsitePanel.Portal.FileLookup fileLookup;
        protected System.Web.UI.WebControls.Button btnBackup;
        protected System.Web.UI.WebControls.Button btnCancel;
    }
}
