//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitePanel.Portal {
    
    public partial class StatisticsEditStatistics {
        protected System.Web.UI.HtmlControls.HtmlTableRow newRow;
        protected System.Web.UI.WebControls.Label lblWebSite;
        protected System.Web.UI.WebControls.Label lblDomainName;
        protected System.Web.UI.WebControls.DropDownList ddlWebSites;
        protected System.Web.UI.WebControls.RequiredFieldValidator valRequireWebSite;
        protected System.Web.UI.WebControls.PlaceHolder providerControl;
        protected System.Web.UI.WebControls.Button btnUpdate;
        protected System.Web.UI.WebControls.Button btnCancel;
        protected System.Web.UI.WebControls.Button btnDelete;
    }
}
