//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitePanel.Portal.ProviderControls {
    
    public partial class Common_IPAddressesList {
        protected System.Web.UI.WebControls.ListBox lbAddresses;
        protected System.Web.UI.WebControls.ImageButton btnRemove;
        protected WebsitePanel.Portal.SelectIPAddress ipAddress;
        protected System.Web.UI.WebControls.Button btnAdd;
    }
}
