//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitePanel.Portal {
    
    public partial class TasksTaskDetails {
		protected System.Web.UI.Timer tasksTimer;
		protected System.Web.UI.UpdatePanel tasksUpdatePanel;
        protected System.Web.UI.WebControls.Literal litTitle;
        protected System.Web.UI.WebControls.Literal litStep;
        protected System.Web.UI.WebControls.Panel pnlProgressBar;
        protected System.Web.UI.WebControls.Localize locStarted;
        protected System.Web.UI.WebControls.Literal litStartTime;
        protected System.Web.UI.WebControls.Localize locDuration;
        protected System.Web.UI.WebControls.Literal litDuration;
        protected System.Web.UI.WebControls.Button btnStop;
        protected System.Web.UI.WebControls.Label lblExecutionLog;
        protected System.Web.UI.WebControls.Panel pnlLog;
        protected System.Web.UI.WebControls.Literal litLog;
        protected System.Web.UI.WebControls.Button btnBack;
    }
}
