//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitePanel.Portal {
    
    public partial class SpaceImportResources {
        protected WebsitePanel.Portal.EnableAsyncTasksSupport asyncTasks;
        protected System.Web.UI.WebControls.TreeView tree;
        protected System.Web.UI.WebControls.Button btnImport;
        protected System.Web.UI.WebControls.Button btnCancel;
    }
}
